<?php
/**
 * Created by nick
 * Project magento.dev
 * Date: 3/1/17
 * Time: 2:17 PM
 */
?>
<?php $companyId = $company->getId()?>
<?php $productCollection = Mage::getModel('company/relation')->getCollection()->addFieldToFilter('company_id', $companyId);?>


<?php     $_helper = $this->helper('catalog/output');?>

<div class="category-products">
<?php echo count($productCollection)?>
<?php $ii = 0; foreach($productCollection as $productRelation):?>
    <?php $_product = Mage::getModel('catalog/product')->load($productRelation->getProductId());?>
    <?php // Grid Mode ?>
    <div class="portlet light portlet-fit bordered portlet-full">
        <div class="portlet-body">
            <div class="product-content clearfix">

                <?php $i=0;  ?>
                    <div class="product-wrap">
                        <div class="col-product">
                            <div class="header-product">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" class="timeline-badge-userpic"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                                <?php //$this->getChild('product-status')->setData("product", $_product);?>
                                <?php //echo $this->getChildHtml('product-status',false);?>
                            </div>
                            <div class="body-product">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                                <?php //$this->getChild('product-attributes')->setData("product", $_product);?>
                                <?php //echo $this->getChildHtml('product-attributes', false);?>
                            </div>
                            <div class="footer-product clearfix">
                                <!--<div class="stars-rating stars-sm pull-left">
                                <?php /*if($_product->getRatingSummary()): */?>
                                    <?php /*echo $this->getReviewsSummaryHtml($_product, 'short') */?>
                                <?php /*endif; */?>
                            </div>-->
                                <?php //$this->getChild('product-rating')->setData("product", $_product);?>
                                <?php //echo $this->getChildHtml('product-rating',false);?>
                                <div class="display-inline pull-right">
                                    <div class="basket-number basket-number-lg"><?php echo $this->getPriceHtml($_product, true) ?></div>
                                    <?php if($_product->isSaleable()): ?>
                                    <button type="button" class="btn yellow btn-lg btn-width border-radius-none bold margin-top-min" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="icon icon-shopping-cart"></i>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>
    <?php if($ii > 20) break;?>
<?php $ii++; endforeach;?>
</div>
