<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 12/9/16
 * Time: 5:49 PM
 */

?>
<div class="type-content">
    <div class="type-radio">
        <span class="type-title">Тип:</span>
        <div class="left-content">
            <div class="radio-group">
                <input type="radio" id="radio1-group1" name="radio-group1">
                <label for="radio1-group1" class="radio-label">поставщик</label>
            </div>
            <div class="radio-group">
                <input type="radio" id="radio1-group2" name="radio-group1">
                <label for="radio1-group2" class="radio-label">производитель</label>
            </div>
            <div class="radio-group">
                <input type="radio" id="radio1-group3" name="radio-group1">
                <label for="radio1-group3" class="radio-label">поставщик - производители</label>
            </div>
            <div class="radio-group">
                <input type="radio" id="radio1-group4" name="radio-group1" checked>
                <label for="radio1-group4" class="radio-label">все компании</label>
            </div>
        </div>
    </div>
    <div class="type-all-company">
        <span class="type-title">Найдено:</span> 26 компаний
    </div>
</div>
