<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 12/9/16
 * Time: 5:49 PM
 */

?>

<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">


    <div class="sort-by">
        <label><?php echo $this->__('Sort By') ?></label>
        <select onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sort By')) ?>">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
        </select>
        <?php if($this->getCurrentDirection() == 'desc'): ?>
            <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" class="sort-by-switcher sort-by-switcher--desc" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?>"><?php echo $this->__('Set Ascending Direction') ?></a>
        <?php else: ?>
            <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" class="sort-by-switcher sort-by-switcher--asc" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?>"><?php echo $this->__('Set Descending Direction') ?></a>
        <?php endif; ?>
    </div>

    <div class="pager">
        <div class="count-container">
            <?php if($this->getLastPageNum()>1): ?>
                <p class="amount amount--has-pages">
                    <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                </p>
            <?php else: ?>
                <p class="amount amount--no-pages">
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                </p>
            <?php endif; ?>

            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Results per page')); ?>">
                    <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                        <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?php echo $_limit ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <?php echo $this->getPagerHtml() ?>

    </div>

</div>
<?php endif ?>


<div class="type-content">
    <div class="type-radio">
        <span class="type-title">Тип:</span>
        <div class="left-content">
            <div class="radio-group">
                <input type="radio" id="radio1-group1" name="radio-group1">
                <label for="radio1-group1" class="radio-label">поставщик</label>
            </div>
            <div class="radio-group">
                <input type="radio" id="radio1-group2" name="radio-group1">
                <label for="radio1-group2" class="radio-label">производитель</label>
            </div>
            <div class="radio-group">
                <input type="radio" id="radio1-group3" name="radio-group1">
                <label for="radio1-group3" class="radio-label">поставщик - производители</label>
            </div>
            <div class="radio-group">
                <input type="radio" id="radio1-group4" name="radio-group1" checked>
                <label for="radio1-group4" class="radio-label">все компании</label>
            </div>
        </div>
    </div>
<!--    <div class="type-all-company">
        <span class="type-title">Найдено:</span> 26 компаний
    </div>-->
</div>
