<?php
/**
 * Created by nick
 * Project magento.dev
 * Date: 3/1/17
 * Time: 2:15 PM
 */
?>
<p><span class="bold">Страна: </span>Украина</p>
<p><span class="bold">Адрес: </span>Харьковская область, Харьков, ул. Плехановская 126/1</p>
<p>
    <span class="bold">Телефоны: </span>
                                                        <span class="left-content">
                                                           (066) 761 16 19 <br>
                                                           (093) 072 74 74 <br>
                                                           (098) 297 63 40 <br>
                                                        </span>
</p>
<p><span class="bold">Email: </span><a class="link-underline" href="mailto:roman@aquazona.com.ua">roman@aquazona.com.ua</a></p>
<p><span class="bold">Сайт: </span><a class="link-underline" href="http://aquazona.com.ua">http://aquazona.com.ua</a></p>
