<?php
/**
 * Created by nick
 * Project magento.dev
 * Date: 3/3/17
 * Time: 5:25 PM
 */
?>
<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="comment-content">
    <div class="c-comment-list">
        <!-- Review text content -->
        <?php if (count($_items)) :?>
            <?php foreach ($_items as $_review) :?>
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading">
                            <span><?php echo $this->escapeHtml($_review->getNickname()); ?></span>
                            <span class="c-date"><?php echo $this->escapeHtml($_review->getCreatedAt()); ?></span>
                        </h4>
                        <!-- Rating stars -->
                        <?php if (count($_votes = $_review->getRatingVotes())) :?>
                            <div class="stars-rating stars-sm">
                                <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-5">
                                <label for="star-rating-11-5" class="radio-label"></label>
                                <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-4">
                                <label for="star-rating-11-4" class="radio-label"></label>
                                <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-3">
                                <label for="star-rating-11-3" class="radio-label"></label>
                                <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-2">
                                <label for="star-rating-11-2" class="radio-label"></label>
                                <input type="radio" disabled="disabled" checked="checked" name="star-rating-11-1">
                                <label for="star-rating-11-1" class="radio-label"></label>
                            </div>
                        <?php endif; ?>
                        <!-- End Rating stars -->
                        <?php echo nl2br($this->escapeHtml($_review->getDetail())); ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <!-- End Review text content -->
    </div>
</div>
