<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 12/9/16
 * Time: 5:28 PM
 */
?>

<div class="portlet light portlet-fit bordered">
    <div class="portlet-title">
    </div>
    <div class="portlet-body ">
        <div class="timeline timeline-list">
            <!-- TIMELINE ITEM -->
            <div class="timeline-item">
                <div class="timeline-badge">
                    <a href="http://upper.com.ua" class="company-link">
                        <img src="images/company-Upper.jpg" class="timeline-badge-userpic">
                    </a>
                    <a href="http://upper.com.ua" class="link-md link-underline">http://upper.com.ua</a>
                </div>
                <div class="timeline-body clearfix">
                    <div class="timeline-body-head">
                        <div class="timeline-body-head-caption">
                            <a class="timeline-body-title font-blue-madison" href="javascript:;">Upper LED</a>
                            <div class="stars-rating stars-sm">
                                <?php echo $this->getRating($_company->getId())?>
                            </div>
                        </div>
                    </div>
                    <div class="timeline-body-content">
                        <p><span class="bold">Тип: </span>производитель</p>
                        <p><span class="bold">Страна: </span>Украина, Киевская область, Киев</p>
                        <p><span class="font-grey-cascade">"Upper" - интернет-магазин, который занимается реализацией источников света нового поколения.
                                Политикой нашего магазина является качество продукта и забота о клиентах.Мы – команда профессионалов своего дела,
                                которые с энтузиазмом относятся к своей работе чтобы сэкономить Ваше...
                                                <a href="" class="link">Подробнее</a></span></p>
                    </div>
                </div>
            </div>
            <!-- END TIMELINE ITEM -->
        </div>
    </div>
</div>
