<?php
/**
 * Created by nick
 * Project magento1.dev
 * Date: 12/9/16
 * Time: 5:28 PM
 */
?>

<?php $_companies = $this->getCompany();?>

<div class="portlet light portlet-fit bordered">
    <div class="portlet-title">
    </div>
    <div class="portlet-body ">
        <?php if($_companies && $_companies->getSize() > 0) : ?>
            <?php foreach($_companies as $_company) :?>
                <div class="timeline timeline-list">
                    <!-- TIMELINE ITEM -->
                    <div class="timeline-item">
                        <div class="timeline-badge">
                            <a href="<?php echo $_company->getUrl()?>" class="company-link">
                                <img src="<?php echo $this->getImageUrl($_company)?>" class="timeline-badge-userpic">
                            </a>
                            <a href="<?php echo $_company->getUrl()?>" class="link-md link-underline"><?php echo $_company->getUrl()?></a>
                        </div>
                        <div class="timeline-body clearfix">
                            <div class="timeline-body-head">
                                <div class="timeline-body-head-caption">
                                    <a class="timeline-body-title font-blue-madison" href="javascript:;"><?php echo $this->escapeHtml($_company->getName())?></a>
                                    <div class="stars-rating stars-sm">
                                        <?php echo $this->getRating($_company->getId())?>
                                    </div>
                                </div>
                            </div>
                            <div class="timeline-body-content">
                                <p><span class="bold"><?php echo $this->__('Type');?>: </span><?php echo $_company->getType()?></p>
                                <p><span class="bold"><?php echo $this->__('Country');?>: </span><?php echo $_company->getCountry()?></p>
                                <p><span class="font-grey-cascade"><?php echo $this->escapeHtml($_company->getDescription())?>
                                        <a href="<?php echo $_company->getCompanyUrl()?>" class="link"><?php echo $this->__('More');?>...</a>
                                    </span></p>
                            </div>
                        </div>
                    </div>
                    <!-- END TIMELINE ITEM -->
                </div>
            <?php endforeach;?>
        <?php else :?>
            <?php echo Mage::helper('company')->__('There are no companies registered at this moment'); ?>
        <?php endif;?>
    </div>
</div>
